# Get payload
FROM registry.redhat.io/openshift-sandboxed-containers/osc-podvm-payload-rhel9:1.10.3 as payload

# Build bootc rhel podvm
FROM registry.redhat.io/rhel9/rhel-bootc:9.5-1738698007 as podvm-bootc

ARG ORG_ID
ARG ACTIVATION_KEY
ARG CLOUD_PROVIDER

# register
RUN if [[ -n "${ACTIVATION_KEY}" && -n "${ORG_ID}" ]]; then \
    #rm -f /etc/rhsm-host && rm -f /etc/pki/entitlement-host; \
    subscription-manager register --org=${ORG_ID} --activationkey=${ACTIVATION_KEY}; \
    fi

COPY etc /etc
COPY usr /usr

# afterburn is required for Azure
#RUN dnf config-manager --add-repo=https://mirror.stream.centos.org/9-stream/AppStream/x86_64/os/ && dnf install -y --nogpgcheck afterburn && dnf clean all && dnf config-manager --set-disabled "*centos*"
RUN if [[ "${CLOUD_PROVIDER}" == "azure" ]]; then \
    dnf install -y afterburn && dnf clean all && \
    ln -s ../afterburn-checkin.service /etc/systemd/system/multi-user.target.wants/afterburn-checkin.service; \
    fi

# Cloud-init is required for Libvirt
RUN if [[ "${CLOUD_PROVIDER}" == "libvirt" ]]; then \
    dnf install -y cloud-init && dnf clean all; \
fi

# Extract podvm binaries and pause bundle
COPY --from=payload /podvm-binaries.tar.gz /podvm-binaries.tar.gz
COPY --from=payload /pause-bundle.tar.gz /pause-bundle.tar.gz
RUN tar -xzvf podvm-binaries.tar.gz -C / && rm /podvm-binaries.tar.gz && \
    tar -xzvf pause-bundle.tar.gz -C / && rm /pause-bundle.tar.gz && \
    sed -i 's#What=/kata-containers#What=/var/kata-containers#g' /etc/systemd/system/run-kata\\x2dcontainers.mount

# a workaround to set podvm-bootc as default target
FROM podvm-bootc as default-target
RUN bootc container lint
