apiVersion: v1
data:
  osImageURL: "quay.io/openshift_sandboxed_containers/rhcos-layer/ocp-4.20:latest-tdx"
  kernelArguments: "kvm_intel.tdx=1 nohibernate"
kind: ConfigMap
metadata:
  name: layered-image-deploy-cm
  namespace: openshift-sandboxed-containers-operator
