apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: osc-upstream-catalog
  namespace: openshift-marketplace
spec:
  displayName: OSC Upstream Operator Catalog
  sourceType: grpc
  image: quay.io/redhat-user-workloads/ose-osc-tenant/osc-test-fbc:latest
  updateStrategy:
    registryPoll:
      interval: 5m
