apiVersion: v1
kind: Namespace
metadata:
  labels:
    control-plane: controller-manager
    pod-security.kubernetes.io/audit: privileged
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/warn: privileged
  name: "openshift-sandboxed-containers-operator"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller-manager
  namespace: system
  labels:
    control-plane: controller-manager
spec:
  selector:
    matchLabels:
      control-plane: controller-manager
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
  template:
    metadata:
      labels:
        control-plane: controller-manager
    spec:
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      tolerations:
        - effect: NoSchedule
          key: node-role.kubernetes.io/master
          operator: Exists
        - effect: NoExecute
          key: node.kubernetes.io/unreachable
          operator: Exists
          tolerationSeconds: 120
        - effect: NoExecute
          key: node.kubernetes.io/not-ready
          operator: Exists
          tolerationSeconds: 120
        - effect: NoSchedule
          key: node.kubernetes.io/memory-pressure
          operator: Exists
      volumes:
        - name: ssh
          secret:
            defaultMode: 384
            optional: true
            secretName: ssh-key-secret
        - name: bound-sa-token
          projected:
            sources:
            - serviceAccountToken:
                path: token
                audience: openshift
      containers:
        - command:
            - /manager
          args:
            - --metrics-bind-address=127.0.0.1:8080
            - --leader-elect
          volumeMounts:
            - mountPath: /root/.ssh/
              name: ssh
              readOnly: true
            - mountPath: /var/run/secrets/openshift/serviceaccount
              name: bound-sa-token
              readOnly: true
          envFrom:
            - secretRef:
                name: peer-pods-secret
                optional: true
            - configMapRef:
                name: peer-pods-cm
                optional: true
          image: controller:latest
          name: manager
          env:
            - name: PEERPODS_NAMESPACE
              value: "openshift-sandboxed-containers-operator"
            - name: RELATED_IMAGE_KATA_MONITOR
              value: registry.redhat.io/openshift-sandboxed-containers/osc-monitor-rhel9@sha256:080d23fdb32d7c6e344f22da06a7aac6d18ab3263fd5b13fd1b686506e8738a2
            - name: RELATED_IMAGE_CAA
              value: registry.redhat.io/openshift-sandboxed-containers/osc-cloud-api-adaptor-rhel9@sha256:004a73b576d24e87aec3c9f857af37c02a526ae775ff2e15a6ccfb02f688e5f0
            - name: RELATED_IMAGE_PEERPODS_WEBHOOK
              value: registry.redhat.io/openshift-sandboxed-containers/osc-cloud-api-adaptor-webhook-rhel9@sha256:e1839f03f5594cf953a1f867cd9e091051d517020f02f6fb731ac8abab5661fc
            - name: RELATED_IMAGE_PODVM_BUILDER
              value: registry.redhat.io/openshift-sandboxed-containers/osc-podvm-builder-rhel9@sha256:3e6142253f4b14fd59a93a37568494ac73d89db346b0ac9ef17402c6acea870c
            - name: RELATED_IMAGE_PODVM_PAYLOAD
              value: registry.redhat.io/openshift-sandboxed-containers/osc-podvm-payload-rhel9@sha256:6a51a51d7b8c6700f3ad01bf223aa5e898449336f2d2519c80b8c610295b8d1a
            - name: RELATED_IMAGE_PODVM_OCI
              value: registry.redhat.io/openshift-sandboxed-containers/osc-dm-verity-image@sha256:57ceb3ca2025b414fb5921acd77307fa5cad853fcadca8299fbd6fbb6e4e85d9
            - name: RELATED_IMAGE_MUST_GATHER
              value: registry.redhat.io/openshift-sandboxed-containers/osc-must-gather-rhel9@sha256:a7b959f9880a16725150387c424d5aef166e0dd86f7f54c8247d7d3624eec1bb
            - name: RELATED_IMAGE_PCCS
              value: registry.redhat.io/openshift-sandboxed-containers/osc-pccs@sha256:a059baf1678525e3b9fbe6abbff3a4bc9ffa9ea3e99f25e5022dc1827021ab9c
            - name: RELATED_IMAGE_TDX_QGS
              value: registry.redhat.io/openshift-sandboxed-containers/osc-tdx-qgs@sha256:42154e82e433eda6d5a59b5f7cadd7702cc0cba1ca4622358322669c5008d14b
            - name: RELATED_IMAGE_STORAGE_HELPER
              value: registry.redhat.io/openshift-sandboxed-containers/osc-storage-helper@sha256:74398373f74c8b2225e2071d22e9751bb6f41d65d3f5a7587a73ac0b29ed870b
          imagePullPolicy: Always
          resources:
            limits:
              cpu: 200m
              memory: 256Mi
            requests:
              cpu: 100m
              memory: 40Mi
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
      terminationGracePeriodSeconds: 10
