apiVersion: v1
kind: Namespace
metadata:
  labels:
    control-plane: controller-manager
    pod-security.kubernetes.io/audit: privileged
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/warn: privileged
  name: "openshift-sandboxed-containers-operator"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller-manager
  namespace: system
  labels:
    control-plane: controller-manager
spec:
  selector:
    matchLabels:
      control-plane: controller-manager
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
  template:
    metadata:
      labels:
        control-plane: controller-manager
    spec:
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      tolerations:
        - effect: NoSchedule
          key: node-role.kubernetes.io/master
          operator: Exists
        - effect: NoExecute
          key: node.kubernetes.io/unreachable
          operator: Exists
          tolerationSeconds: 120
        - effect: NoExecute
          key: node.kubernetes.io/not-ready
          operator: Exists
          tolerationSeconds: 120
        - effect: NoSchedule
          key: node.kubernetes.io/memory-pressure
          operator: Exists
      volumes:
        - name: ssh
          secret:
            defaultMode: 384
            optional: true
            secretName: ssh-key-secret
      containers:
        - command:
            - /manager
          args:
            - --metrics-bind-address=127.0.0.1:8080
            - --leader-elect
          volumeMounts:
            - mountPath: /root/.ssh/
              name: ssh
              readOnly: true
          envFrom:
            - secretRef:
                name: peer-pods-secret
                optional: true
            - configMapRef:
                name: peer-pods-cm
                optional: true
          image: controller:latest
          name: manager
          env:
            - name: PEERPODS_NAMESPACE
              value: "openshift-sandboxed-containers-operator"
            - name: RELATED_IMAGE_KATA_MONITOR
              value: registry.redhat.io/openshift-sandboxed-containers/osc-monitor-rhel9@sha256:10b51e39b051ba838343a82eae036299c10b135705d2ac5da7782ea068ba4dab
            - name: RELATED_IMAGE_CAA
              value: registry.redhat.io/openshift-sandboxed-containers/osc-cloud-api-adaptor-rhel9@sha256:6efba887ccaa4bc5a899751d365e2ccb70c45a842c694579972c5947ca65b49e
            - name: RELATED_IMAGE_PEERPODS_WEBHOOK
              value: registry.redhat.io/openshift-sandboxed-containers/osc-cloud-api-adaptor-webhook-rhel9@sha256:3c0e7c787fb0523dc5f92f50107a7a4d2f2b50b79e0b002edaa931a4e91898a2
            - name: RELATED_IMAGE_PODVM_BUILDER
              value: registry.redhat.io/openshift-sandboxed-containers/osc-podvm-builder-rhel9@sha256:e1cacfd2dc9a091e78e28658fa5a5bc63f346530c663540de3a3cbd7523cf4f3
            - name: RELATED_IMAGE_PODVM_PAYLOAD
              value: registry.redhat.io/openshift-sandboxed-containers/osc-podvm-payload-rhel9@sha256:e2121abd92cec8a3dd12a031aa8a3ff6f41156b31b147231956e6725651e5816 
            - name: RELATED_IMAGE_PODVM_OCI
              value: registry.redhat.io/openshift-sandboxed-containers/osc-dm-verity-image@sha256:e5b116d47ce9e2c2ccf7833952440edf11b38265a263b2d60b2012e339721b39
          imagePullPolicy: Always
          resources:
            limits:
              cpu: 200m
              memory: 256Mi
            requests:
              cpu: 100m
              memory: 40Mi
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
      terminationGracePeriodSeconds: 10
