apiVersion: v1
kind: Namespace
metadata:
  labels:
    control-plane: controller-manager
    pod-security.kubernetes.io/audit: privileged
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/warn: privileged
  name: "openshift-sandboxed-containers-operator"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller-manager
  namespace: system
  labels:
    control-plane: controller-manager
spec:
  selector:
    matchLabels:
      control-plane: controller-manager
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
  template:
    metadata:
      labels:
        control-plane: controller-manager
    spec:
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      tolerations:
        - effect: NoSchedule
          key: node-role.kubernetes.io/master
          operator: Exists
        - effect: NoExecute
          key: node.kubernetes.io/unreachable
          operator: Exists
          tolerationSeconds: 120
        - effect: NoExecute
          key: node.kubernetes.io/not-ready
          operator: Exists
          tolerationSeconds: 120
        - effect: NoSchedule
          key: node.kubernetes.io/memory-pressure
          operator: Exists
      volumes:
        - name: ssh
          secret:
            defaultMode: 384
            optional: true
            secretName: ssh-key-secret
      containers:
        - command:
            - /manager
          args:
            - --metrics-bind-address=127.0.0.1:8080
            - --leader-elect
          volumeMounts:
            - mountPath: /root/.ssh/
              name: ssh
              readOnly: true
          envFrom:
            - secretRef:
                name: peer-pods-secret
                optional: true
            - configMapRef:
                name: peer-pods-cm
                optional: true
          image: controller:latest
          name: manager
          env:
            - name: PEERPODS_NAMESPACE
              value: "openshift-sandboxed-containers-operator"
            - name: RELATED_IMAGE_KATA_MONITOR
              value: registry.redhat.io/openshift-sandboxed-containers/osc-monitor-rhel9@sha256:2c93b458f427dcf4f410a36fc2c176aa85157cd64aed1afe58ecd32d557e92bb
            - name: RELATED_IMAGE_CAA
              value: registry.redhat.io/openshift-sandboxed-containers/osc-cloud-api-adaptor-rhel9@sha256:5b48a769159112639a939b22d30dedbdbfd431537379266fe70eb5992c58fe32
            - name: RELATED_IMAGE_PEERPODS_WEBHOOK
              value: registry.redhat.io/openshift-sandboxed-containers/osc-cloud-api-adaptor-webhook-rhel9@sha256:02d17d94b6abca35303edec8c0b1bd1036e884aa414d40b859c150a86c3f850e
            - name: RELATED_IMAGE_PODVM_BUILDER
              value: registry.redhat.io/openshift-sandboxed-containers/osc-podvm-builder-rhel9@sha256:b7633da598a21aee5d934993191d4bba695bdc02e4aaa184581e832f105f69f7
            - name: RELATED_IMAGE_PODVM_PAYLOAD
              value: registry.redhat.io/openshift-sandboxed-containers/osc-podvm-payload-rhel9@sha256:7c095b26c83eee57cfbddcc9a377fc0ab1fb8199a870a7cb0bd6ef53e5ef2c67 
            - name: RELATED_IMAGE_PODVM_OCI
              value: registry.redhat.io/openshift-sandboxed-containers/osc-dm-verity-image@sha256:49a6c7c126ef7dea48562fdf49d68b6ef5637f6e46745665189597feb94dfdda
          imagePullPolicy: Always
          resources:
            limits:
              cpu: 200m
              memory: 256Mi
            requests:
              cpu: 100m
              memory: 40Mi
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
      terminationGracePeriodSeconds: 10
