// +build !ignore_autogenerated

/*


Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FailedNodeStatus) DeepCopyInto(out *FailedNodeStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FailedNodeStatus.
func (in *FailedNodeStatus) DeepCopy() *FailedNodeStatus {
	if in == nil {
		return nil
	}
	out := new(FailedNodeStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KataConfig) DeepCopyInto(out *KataConfig) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KataConfig.
func (in *KataConfig) DeepCopy() *KataConfig {
	if in == nil {
		return nil
	}
	out := new(KataConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KataConfig) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KataConfigCompletedStatus) DeepCopyInto(out *KataConfigCompletedStatus) {
	*out = *in
	if in.CompletedNodesList != nil {
		in, out := &in.CompletedNodesList, &out.CompletedNodesList
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KataConfigCompletedStatus.
func (in *KataConfigCompletedStatus) DeepCopy() *KataConfigCompletedStatus {
	if in == nil {
		return nil
	}
	out := new(KataConfigCompletedStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KataConfigList) DeepCopyInto(out *KataConfigList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]KataConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KataConfigList.
func (in *KataConfigList) DeepCopy() *KataConfigList {
	if in == nil {
		return nil
	}
	out := new(KataConfigList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KataConfigList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KataConfigSpec) DeepCopyInto(out *KataConfigSpec) {
	*out = *in
	if in.KataConfigPoolSelector != nil {
		in, out := &in.KataConfigPoolSelector, &out.KataConfigPoolSelector
		*out = new(metav1.LabelSelector)
		(*in).DeepCopyInto(*out)
	}
	out.Config = in.Config
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KataConfigSpec.
func (in *KataConfigSpec) DeepCopy() *KataConfigSpec {
	if in == nil {
		return nil
	}
	out := new(KataConfigSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KataConfigStatus) DeepCopyInto(out *KataConfigStatus) {
	*out = *in
	in.InstallationStatus.DeepCopyInto(&out.InstallationStatus)
	in.UnInstallationStatus.DeepCopyInto(&out.UnInstallationStatus)
	out.Upgradestatus = in.Upgradestatus
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KataConfigStatus.
func (in *KataConfigStatus) DeepCopy() *KataConfigStatus {
	if in == nil {
		return nil
	}
	out := new(KataConfigStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KataFailedNodeStatus) DeepCopyInto(out *KataFailedNodeStatus) {
	*out = *in
	if in.FailedNodesList != nil {
		in, out := &in.FailedNodesList, &out.FailedNodesList
		*out = make([]FailedNodeStatus, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KataFailedNodeStatus.
func (in *KataFailedNodeStatus) DeepCopy() *KataFailedNodeStatus {
	if in == nil {
		return nil
	}
	out := new(KataFailedNodeStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KataInstallConfig) DeepCopyInto(out *KataInstallConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KataInstallConfig.
func (in *KataInstallConfig) DeepCopy() *KataInstallConfig {
	if in == nil {
		return nil
	}
	out := new(KataInstallConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KataInstallationInProgressStatus) DeepCopyInto(out *KataInstallationInProgressStatus) {
	*out = *in
	if in.BinariesInstalledNodesList != nil {
		in, out := &in.BinariesInstalledNodesList, &out.BinariesInstalledNodesList
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KataInstallationInProgressStatus.
func (in *KataInstallationInProgressStatus) DeepCopy() *KataInstallationInProgressStatus {
	if in == nil {
		return nil
	}
	out := new(KataInstallationInProgressStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KataInstallationStatus) DeepCopyInto(out *KataInstallationStatus) {
	*out = *in
	in.InProgress.DeepCopyInto(&out.InProgress)
	in.Completed.DeepCopyInto(&out.Completed)
	in.Failed.DeepCopyInto(&out.Failed)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KataInstallationStatus.
func (in *KataInstallationStatus) DeepCopy() *KataInstallationStatus {
	if in == nil {
		return nil
	}
	out := new(KataInstallationStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KataUnInstallationInProgressStatus) DeepCopyInto(out *KataUnInstallationInProgressStatus) {
	*out = *in
	if in.BinariesUnInstalledNodesList != nil {
		in, out := &in.BinariesUnInstalledNodesList, &out.BinariesUnInstalledNodesList
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KataUnInstallationInProgressStatus.
func (in *KataUnInstallationInProgressStatus) DeepCopy() *KataUnInstallationInProgressStatus {
	if in == nil {
		return nil
	}
	out := new(KataUnInstallationInProgressStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KataUnInstallationStatus) DeepCopyInto(out *KataUnInstallationStatus) {
	*out = *in
	in.InProgress.DeepCopyInto(&out.InProgress)
	in.Completed.DeepCopyInto(&out.Completed)
	in.Failed.DeepCopyInto(&out.Failed)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KataUnInstallationStatus.
func (in *KataUnInstallationStatus) DeepCopy() *KataUnInstallationStatus {
	if in == nil {
		return nil
	}
	out := new(KataUnInstallationStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KataUpgradeStatus) DeepCopyInto(out *KataUpgradeStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KataUpgradeStatus.
func (in *KataUpgradeStatus) DeepCopy() *KataUpgradeStatus {
	if in == nil {
		return nil
	}
	out := new(KataUpgradeStatus)
	in.DeepCopyInto(out)
	return out
}
