{
 "title": "Kata Pods",
 "panels": [
  {
   "title": "Number of running VMs",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(count by(instance) (kata_guest_load{item=\"load1\"}))",
     "legendFormat": "number of VMs"
    }
   ]
  },
  {
   "title": "CPU Usage (per VM)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (sandbox_id) (irate(kata_guest_cpu_time{cpu=\"total\",  item=~\"irq|softirq|system|user\"}[5m]))",
     "legendFormat": "sandbox id {{sandbox_id}}"
    }
   ]
  },
  {
   "title": "Memory Usage (per VM)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(kata_guest_meminfo{item=\"mem_total\"} - on(sandbox_id) kata_guest_meminfo{item=\"mem_free\"})",
     "legendFormat": "sandbox id {{sandbox_id}}"
    }
   ]
  }
 ]
}