apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: openshift-sandboxed-containers-monitor
spec:
  endpoints:
  - port: metrics
    scheme: https
    tlsConfig:
      ca:
        configMap:
          key: service-ca.crt
          name: openshift-service-ca.crt
      insecureSkipVerify: false
      serverName: metrics.openshift-sandboxed-containers-operator.svc
  namespaceSelector:
    matchNames:
    - openshift-sandboxed-containers-operator
  selector:
    matchLabels:
      name: openshift-sandboxed-containers-monitor
