apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.openshift.io/serving-cert-secret-name: peer-pods-webhook-metrics-certs
  creationTimestamp: null
  labels:
    app: peer-pods-webhook
  name: peer-pods-webhook-metrics-svc
spec:
  ports:
  - name: metrics
    port: 8443
    protocol: TCP
    targetPort: 8443
  selector:
    app: peer-pods-webhook
status:
  loadBalancer: {}
