# Copyright (c) 2022 - 2023 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

apiVersion: nfd.openshift.io/v1
kind: NodeFeatureDiscovery
metadata:
  name: nfd-instance
  namespace: openshift-nfd
spec:
  operand:
    image: registry.redhat.io/openshift4/ose-node-feature-discovery-rhel9:v4.18
    imagePullPolicy: Always
    servicePort: 12000
  workerConfig:
    configData: |
