# permissions for end users to edit kataconfigs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kataconfig-editor-role
rules:
- apiGroups:
  - kataconfiguration.openshift.io
  - peerpodconfiguration.confidentialcontainers.org
<<<<<<< HEAD
  resources:
  - kataconfigs
  - peerpodconfigs
=======
  - confidentialcontainers.org
  resources:
  - kataconfigs
  - peerpodconfigs
  - peerpods
>>>>>>> devel
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kataconfiguration.openshift.io
  - peerpodconfiguration.confidentialcontainers.org
<<<<<<< HEAD
  resources:
  - kataconfigs/status
  - peerpodconfigs/status
=======
  - confidentialcontainers.org
  resources:
  - kataconfigs/status
  - peerpodconfigs/status
  - peerpods/status
>>>>>>> devel
  verbs:
  - get
