# permissions for end users to view kataconfigs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kataconfig-viewer-role
rules:
- apiGroups:
  - kataconfiguration.openshift.io
  - peerpodconfiguration.confidentialcontainers.org
<<<<<<< HEAD
  resources:
  - kataconfigs
  - peerpodconfigs
=======
  - confidentialcontainers.org
  resources:
  - kataconfigs
  - peerpodconfigs
  - peerpods
>>>>>>> devel
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - peerpodconfiguration.confidentialcontainers.org
  - kataconfiguration.openshift.io
  - confidentialcontainers.org
  resources:
  - kataconfigs/status
  - peerpodconfigs/status
<<<<<<< HEAD
=======
  - peerpods/status
>>>>>>> devel
  verbs:
  - get
