---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: monitor-role
  namespace: openshift-sandboxed-containers-operator
rules:
- apiGroups:
  - ""
  resources:
  - services
  - endpoints
  - pods
  verbs:
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: monitor-rolebinding
  namespace: openshift-sandboxed-containers-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: monitor-role
subjects:
- kind: ServiceAccount
  name: prometheus-k8s
  namespace: openshift-monitoring
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: monitor-daemonset-privileged-deployment
  namespace: openshift-sandboxed-containers-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:openshift:scc:privileged
subjects:
- kind: ServiceAccount
  name: default
  namespace: openshift-sandboxed-containers-operator
