FROM registry.access.redhat.com/ubi9/ubi:9.8-1788245065

# azure-podvm-image-handler.sh script under /scripts/azure-podvm-image-handler.sh
# aws-podvm-image-handler.sh script under /scripts/aws-podvm-image-handler.sh
# sources for cloud-api-adaptor under /src/cloud-api-adaptor
# The podvm binaries are expected to be under /payload/podvm-binaries.tar.gz
# Binaries like kubectl, packer and yq under /usr/local/bin will be installed by the scripts


LABEL kata_src=https://github.com/kata-containers/kata-containers
LABEL kata_src_commit=stable-3.7

ARG ORG_ID
ARG ACTIVATION_KEY

# This registering RHEL when building on an unsubscribed system
# If you are running a UBI container on a registered and subscribed RHEL host, 
# the main RHEL Server repository is enabled inside the standard UBI container.
# Uncomment this and provide the associated ARG variables to register.
#RUN if [[ -n "${ACTIVATION_KEY}" && -n "${ORG_ID}" ]]; then \
#    rm -f /etc/rhsm-host && rm -f /etc/pki/entitlement-host; \
#    subscription-manager register --org=${ORG_ID} --activationkey=${ACTIVATION_KEY}; \
#    fi

RUN mkdir -p /scripts

ADD ami-helper.sh lib.sh libvirt-podvm-image-handler.sh aws-podvm-image-handler.sh azure-podvm-image-handler.sh gcp-podvm-image-handler.sh ibmcloud-podvm-image-handler.sh /scripts/

RUN mkdir -p /scripts/bootc
ADD bootc/config.toml /scripts/bootc/

# TODO: Since this installation applies to all providers, consider renaming the
# script or moving the generic RPMS installation elsewhere for better clarity.
RUN /scripts/azure-podvm-image-handler.sh -- install_rpms

ARG CAA_SRC=https://github.com/confidential-containers/cloud-api-adaptor
ARG CAA_REF=main
ARG CERT_RPM

RUN dnf install -y golang python3 python3-pip python3-wheel krb5-devel gpgme-devel libassuan-devel gcc libffi-devel python3-devel rust cargo openssl-devel && dnf clean all

# Copy go.mod, go.sum and azure-cli-pip.txt to use our dependency versions
COPY go.mod go.sum azure-cli-pip.txt /tmp/tools/
WORKDIR /tmp/tools

# Build and install tools using our module's dependency versions
RUN GOSUMDB=off GOBIN=/usr/local/bin go install github.com/mikefarah/yq/v4 && \
    GOSUMDB=off GOBIN=/usr/local/bin go install github.com/opencontainers/umoci/cmd/umoci && \
    GOSUMDB=off GOBIN=/usr/local/bin go install github.com/openshift/oc/cmd/oc && \
    ln -s /usr/local/bin/oc /usr/local/bin/kubectl

# Install Azure CLI from prefetched pip packages
RUN if [ -d "/cachi2/output/deps/pip" ]; then \
        echo "Installing Azure CLI from prefetched packages..." && \
        pip3 install --no-index --find-links /cachi2/output/deps/pip --require-hashes -r /tmp/tools/azure-cli-pip.txt && \
        echo "Azure CLI installed successfully from prefetched packages"; \
    else \
        echo "Installing Azure CLI from pip packages..."; \
        pip3 install -r /tmp/tools/azure-cli-pip.txt && \
        echo "Azure CLI installed successfully from pip packages"; \
    fi

# Clean up the tools directory to reduce the image size
RUN cd / && rm -rf /tmp/tools

WORKDIR /

ENV CAA_SRC=$CAA_SRC
ENV CAA_REF=$CAA_REF
ENV CERT_RPM=$CERT_RPM

RUN if [[ -n "$CERT_RPM" ]] ; then \
    dnf install -y $CERT_RPM ; \
    fi


COPY cloud-api-adaptor /src/cloud-api-adaptor

ADD podvm-builder.sh /podvm-builder.sh

ARG VERSION

# Red Hat labels
LABEL name="openshift-sandboxed-containers/osc-podvm-builder-rhel9" \
cpe="cpe:/a:redhat:confidential_compute_attestation:1.130::el9" \
version="$VERSION" \
com.redhat.component="osc-podvm-builder-container" \
summary="Container image containing artefacts that is required for creating Pod VM images" \
maintainer="redhat@redhat.com" \
description="Container image containing artefacts that is required for creating Pod VM images" \
io.k8s.display-name="openshift-sandboxed-containers-podvm-builder" \
io.k8s.description="Container image containing artefacts that is required for creating Pod VM images" \
io.openshift.tags=""

# Remove the build dependencies to reduce the image size (keep python3 and pip for azure-cli)
RUN dnf remove -y golang krb5-devel gpgme-devel libassuan-devel gcc libffi-devel python3-devel rust cargo openssl-devel && dnf clean all

RUN echo "Cleaning up unnecessary binaries from /usr/local/bin..." && \
    cd /usr/local/bin && \
    rm -rf __pycache__ && \
    rm -f activate-global-python-argcomplete az.bat azps.ps1 chardetect distro fab humanfriendly inv invoke jdiff jp.py normalizer pkginfo pygmentize pygrun pysemver python-argcomplete-check-easy-install-script register-python-argcomplete sshtunnel tabulate wsdump cygdb cython cythonize hatchling maturin setuptools-scm trove-classifiers wheel idna

ENTRYPOINT ["/podvm-builder.sh"]
