FROM registry.access.redhat.com/ubi9/ubi:9.5-1741850090

# azure-podvm-image-handler.sh script under /scripts/azure-podvm-image-handler.sh
# aws-podvm-image-handler.sh script under /scripts/aws-podvm-image-handler.sh
# sources for cloud-api-adaptor under /src/cloud-api-adaptor
# The podvm binaries are expected to be under /payload/podvm-binaries.tar.gz
# Binaries like kubectl, packer and yq under /usr/local/bin will be installed by the scripts


LABEL kata_src=https://github.com/kata-containers/kata-containers
LABEL kata_src_commit=stable-3.7

ARG ORG_ID
ARG ACTIVATION_KEY

# This registering RHEL when building on an unsubscribed system
# If you are running a UBI container on a registered and subscribed RHEL host, 
# the main RHEL Server repository is enabled inside the standard UBI container.
# Uncomment this and provide the associated ARG variables to register.
#RUN if [[ -n "${ACTIVATION_KEY}" && -n "${ORG_ID}" ]]; then \
#    rm -f /etc/rhsm-host && rm -f /etc/pki/entitlement-host; \
#    subscription-manager register --org=${ORG_ID} --activationkey=${ACTIVATION_KEY}; \
#    fi

RUN mkdir -p /scripts

ADD lib.sh libvirt-podvm-image-handler.sh aws-podvm-image-handler.sh azure-podvm-image-handler.sh gcp-podvm-image-handler.sh /scripts/

RUN mkdir -p /scripts/bootc
ADD bootc/config.toml /scripts/bootc/

# TODO: Since this installation applies to all providers, consider renaming the
# script or moving the generic RPMS installation elsewhere for better clarity.
RUN /scripts/azure-podvm-image-handler.sh -- install_rpms

ARG CAA_SRC=https://github.com/confidential-containers/cloud-api-adaptor
ARG CAA_REF=main
ARG CERT_RPM


ENV CAA_SRC=$CAA_SRC
ENV CAA_REF=$CAA_REF
ENV CERT_RPM=$CERT_RPM

RUN if [[ -n "$CERT_RPM" ]] ; then \
    dnf install -y $CERT_RPM ; \
    fi

# If we are running in a hermetic environment, we can't use "git clone".
# Get the archive from github instead. We need to make sure the archive is
# declared in Hermeto (see artifacts.lock.yaml)
# Also see documentation for Konflux:
# https://konflux.pages.redhat.com/docs/users/building/prefetching-dependencies.html#generic
RUN if [[ -e /cachi2/cachi2.env ]]; then \
      mkdir -p /src/ ; \
      cd /src/ ; \
      unzip /cachi2/output/deps/generic/${CAA_REF}.zip ; \
      mv cloud-api-adaptor-${CAA_REF} cloud-api-adaptor ; \
    else  \
      git clone ${CAA_SRC} -b ${CAA_REF} /src/cloud-api-adaptor ; \
    fi

ADD podvm-builder.sh /podvm-builder.sh

ENTRYPOINT ["/podvm-builder.sh"]
