apiVersion: v1
kind: ConfigMap
metadata:
  name: gcp-podvm-image-cm
  namespace: openshift-sandboxed-containers-operator
data:
  IMAGE_BASE_NAME: "podvm-image"
  # Must be in Major(int).Minor(int).Patch(int) format
  # When deployed from operator, update the IMAGE_VERSION to something like
  # "$clusterid-0-1"
  IMAGE_VERSION: "0-0-1"

  # Booleans
  INSTALL_PACKAGES: "no"
  UPDATE_PEERPODS_CM: "yes"

  # precreated artifacts
  #PODVM_IMAGE_URI: bootc::image-registry.openshift-image-registry.svc:5000/openshift-sandboxed-containers-operator/podvm-bootc
