apiVersion: v1
kind: ConfigMap
metadata:
  name: ibmcloud-podvm-image-cm
  namespace: openshift-sandboxed-containers-operator
# these are just placeholders for now
data:
  # Booleans
  INSTALL_PACKAGES: "no"
  UPDATE_PEERPODS_CM: "yes"

  # precreated artifacts
  #COS_BUCKET_NAME: existing-bucket-name
  PODVM_IMAGE_URI: bootc::image-registry.openshift-image-registry.svc:5000/openshift-sandboxed-containers-operator/podvm-bootc
