apiVersion: v1
kind: ConfigMap
metadata:
  name: libvirt-podvm-image-cm
  namespace: openshift-sandboxed-containers-operator
data:
  # PodVM image distro
  PODVM_DISTRO: "rhel"

  # Pod VM sources
  # If changing the source, then ensure the respective payload binaries are available
  # for the new source
  #CAA_SRC: "" ## set to cloud-api-adaptor sources URL for custom podvm builds
  #CAA_REF: "" ## set to tag/branch for the cloud-api-adaptor code to use

  # Booleans
  DOWNLOAD_SOURCES: "no" ## set to "yes" for custom podvm builds. Need to set CAA_SRC and CAA_REF accordingly
  CONFIDENTIAL_COMPUTE_ENABLED: "no"
  UPDATE_PEERPODS_CM: "yes"

  # Libvirt specific
  ORG_ID: ""
  ACTIVATION_KEY: ""
  BASE_OS_VERSION: "9.4"

  # To Enable SE for IBM Z
  SE_BOOT: "true"

  # For Pre-built PodVM images.
  PODVM_IMAGE_URI: "" # eg: oci::quay.io/openshift_sandboxed_containers/libvirt-podvm-image:latest::/image/podvm.qcow2
