apiVersion: v1
kind: ConfigMap
metadata:
  name: libvirt-podvm-image-cm
  namespace: openshift-sandboxed-containers-operator
data:
  # Booleans
  UPDATE_PEERPODS_CM: "yes"

  # To Enable SE for IBM Z
  SE_BOOT: "true"

  # To enable SE verification on IBM Z
  SE_VERIFY: "true"

  # For Pre-built PodVM images.
  PODVM_IMAGE_URI: "" # eg: oci::quay.io/openshift_sandboxed_containers/libvirt-podvm-image:latest::/image/podvm.qcow2
