apiVersion: appstudio.redhat.com/v1alpha1
kind: Snapshot
metadata:
  name: osc-release-snapshot-1.10.3-1
  namespace: ose-osc-tenant
spec:
  application: openshift-sandboxed-containers-v1-10
  components:
  - containerImage: quay.io/redhat-user-workloads/ose-osc-tenant/osc-monitor-v1-10@sha256:ce49124dc965c77cd93e9fa34b0392194761cc949543cf39d3a0ce7d33a64572
    name: osc-monitor-v1-10
    source:
      git:
        dockerfileUrl: Dockerfile.monitor
        revision: 4560d2b96839bcc8035a60348ecfe0b3a7c8a77d
        url: https://github.com/openshift/kata-containers
  - containerImage: quay.io/redhat-user-workloads/ose-osc-tenant/osc-operator-bundle-v1-10@sha256:417ee37b223c39a06e8534fbe8b9f11e54e481df17977e4d4d62c62ccf8e63a4
    name: osc-operator-bundle-v1-10
    source:
      git:
        revision: a894d05350ba200e176db6b09d49568eedb49b80
        url: https://github.com/openshift/sandboxed-containers-operator
  - containerImage: quay.io/redhat-user-workloads/ose-osc-tenant/osc-podvm-builder-v1-10@sha256:21e810dd9d030c3835fadfc4c434e36a26ab57d9451dc955fc1625b48fac3815
    name: osc-podvm-builder-v1-10
    source:
      git:
        context: config/peerpods/podvm
        dockerfileUrl: Dockerfile.podvm-builder
        revision: d36004f697731521faa9b1bc6acd94f9ca99dcd4
        url: https://github.com/openshift/sandboxed-containers-operator
  - containerImage: quay.io/redhat-user-workloads/ose-osc-tenant/osc-podvm-payload-v1-10@sha256:c9790aaa961f6976c14fc9cbef448fc48fcdfacf94f3af25fa2b1e31c72c8d9f
    name: osc-podvm-payload-v1-10
    source:
      git:
        dockerfileUrl: podvm-payload/Dockerfile
        revision: bdca2073285730b4fc5e8028b6ac4dd9a0256d13
        url: https://github.com/openshift/cloud-api-adaptor
  - containerImage: quay.io/redhat-user-workloads/ose-osc-tenant/osc-caa-v1-10@sha256:7d1fa1e85af0d34c23e75868b1388eff17abe633c04a8dc55fbefcc470195c05
    name: osc-caa-v1-10
    source:
      git:
        context: src
        dockerfileUrl: cloud-api-adaptor/Dockerfile.openshift
        revision: bdca2073285730b4fc5e8028b6ac4dd9a0256d13
        url: https://github.com/openshift/cloud-api-adaptor
  - containerImage: quay.io/redhat-user-workloads/ose-osc-tenant/osc-dm-verity-image-v1-10@sha256:9b32c441a08792374a8b681ed5733d8df77857ea96200630080fdd96012f8b55
    name: osc-dm-verity-image-v1-10
    source:
      git:
        revision: 3962471832c450387a0659432d057ce88443f16a
        url: https://github.com/confidential-devhub/coco-podvm-scripts
  - containerImage: quay.io/redhat-user-workloads/ose-osc-tenant/osc-operator-v1-10@sha256:1ffb432d9a8833854fa5e5262dcbf42530dfbaadfddf6978f7bc7804b84d2e3f
    name: osc-operator-v1-10
    source:
      git:
        revision: d317b15b575172392731b2c00876846ebc45922d
        url: https://github.com/openshift/sandboxed-containers-operator
  - containerImage: quay.io/redhat-user-workloads/ose-osc-tenant/osc-caa-webhook-v1-10@sha256:6802f00a939f24ecd6dad150433db5ea3fd72d171f0c410cb894d3af910fc7fd
    name: osc-caa-webhook-v1-10
    source:
      git:
        context: src/webhook
        revision: bdca2073285730b4fc5e8028b6ac4dd9a0256d13
        url: https://github.com/openshift/cloud-api-adaptor
  - containerImage: quay.io/redhat-user-workloads/ose-osc-tenant/osc-must-gather-v1-10@sha256:a9dceee04f0a107c3c2a32838187c3bef7d54c7ad10ff75849e488009ed927e8
    name: osc-must-gather-v1-10
    source:
      git:
        context: must-gather
        revision: d36004f697731521faa9b1bc6acd94f9ca99dcd4
        url: https://github.com/openshift/sandboxed-containers-operator