apiVersion: appstudio.redhat.com/v1alpha1
kind: Snapshot
metadata:
  name: osc-release-snapshot-1.10.3-1
  namespace: ose-osc-tenant
spec:
  application: openshift-sandboxed-containers-v1-10
  components:
  - containerImage: quay.io/redhat-user-workloads/ose-osc-tenant/osc-monitor@sha256:9e297de3d963cb5ebd80a609f848ee716eb1dedb0ee6cc76f523d7fe9005a167
    name: osc-monitor
    source:
      git:
        dockerfileUrl: Dockerfile.monitor
        revision: 956cc37ba2929245ee9784155501fcc3a3c115d6
        url: https://github.com/openshift/kata-containers
  - containerImage: quay.io/redhat-user-workloads/ose-osc-tenant/osc-operator-bundle@sha256:a5db075a773eceebb63cb33033afad81baaaa108ce5acd533947eb21a1b16b58
    name: osc-operator-bundle
    source:
      git:
        revision: 17ee44df4589ee9efbb68d89cd736e42a68a35cf
        url: https://github.com/openshift/sandboxed-containers-operator
  - containerImage: quay.io/redhat-user-workloads/ose-osc-tenant/osc-podvm-builder@sha256:c18fef762f36f294b9f0d9881696220df8774bff479dd13e779cb897583af194
    name: osc-podvm-builder
    source:
      git:
        context: config/peerpods/podvm
        dockerfileUrl: Dockerfile.podvm-builder
        revision: 154f467dd6e55c0d1f93d0d9e58c5c9427cfeebd
        url: https://github.com/openshift/sandboxed-containers-operator
  - containerImage: quay.io/redhat-user-workloads/ose-osc-tenant/osc-podvm-payload@sha256:cd44044bdcee400f802b0ec74227467b2b860df8ff103079b10bc22ce06dfc0a
    name: osc-podvm-payload
    source:
      git:
        dockerfileUrl: podvm-payload/Dockerfile
        revision: ebb979546fb136168122ac63b4aa83227847f5c3
        url: https://github.com/openshift/cloud-api-adaptor
  - containerImage: quay.io/redhat-user-workloads/ose-osc-tenant/osc-caa@sha256:04e2982cf0a6a69a5dfe7549ca038ca5a2d60fa7ea4a15c98c80043212f79a40
    name: osc-caa
    source:
      git:
        context: src
        dockerfileUrl: cloud-api-adaptor/Dockerfile.openshift
        revision: ebb979546fb136168122ac63b4aa83227847f5c3
        url: https://github.com/openshift/cloud-api-adaptor
  - containerImage: quay.io/redhat-user-workloads/ose-osc-tenant/osc-dm-verity-image@sha256:ad0503ae88cac7d2975f3fdf5bfc2eafe30d263f7d75d9fff7ba31a88947cc0f
    name: osc-dm-verity-image
    source:
      git:
        revision: 91303a1882260587573fd04c395d49701c486b8d
        url: https://github.com/confidential-devhub/coco-podvm-scripts
  - containerImage: quay.io/redhat-user-workloads/ose-osc-tenant/osc-operator@sha256:4fb018ce03cfaa06b983e801508036352247d3f9fc09981949f85b7e8ab4520b
    name: osc-operator
    source:
      git:
        revision: 43613b0f9f312b4b4e9e830927eb3c8718859026
        url: https://github.com/openshift/sandboxed-containers-operator
  - containerImage: quay.io/redhat-user-workloads/ose-osc-tenant/osc-caa-webhook@sha256:ef4a8efcfb74e3e6b68fe3c566b343ac5da0a4d1de203342c46defae60029a81
    name: osc-caa-webhook
    source:
      git:
        context: src/webhook
        revision: ebb979546fb136168122ac63b4aa83227847f5c3
        url: https://github.com/openshift/cloud-api-adaptor
  - containerImage: quay.io/redhat-user-workloads/ose-osc-tenant/osc-must-gather@sha256:a33a8960c17aee79115934726006586e5c29c10413ff30ccea6844a2068164ae
    name: osc-must-gather
    source:
      git:
        context: must-gather
        revision: 43613b0f9f312b4b4e9e830927eb3c8718859026
        url: https://github.com/openshift/sandboxed-containers-operator