#!/usr/bin/env bash
# We get a lot of dependency updates from Mintmaker. Reviewing/merging them one
# by one is taking a lot of time.
#
# This script is meant to help dealing with those pull request. It will:
# - create a local git branch
# - identify all the pull requests from Mintmaker
# - cherry-pick them one by one to the local branch
#
# The script is ignoring any commit that conflicts.
# It also ignores PRs marked as "do not merge", and nudge PRs from Konflux
# (that should be worked on separately).
#
# The script is meant to work on all our repositories. For that purpose, the
# default values used for branch/remote/repo can be overridden by environment
# variables, or using command line parameters.
#
# The resulting branch should be reviewed and pushed as a single PR.
# The script doesn't create the PR, and doesn't close the related PRs from Mintmaker.
set -uo pipefail

# Default configuration
AUTHOR="${AUTHOR:-app/red-hat-konflux}"
REMOTE="${REMOTE:-openshift}"
TARGET_BRANCH="${TARGET_BRANCH:-osc-release}"
REPO="${REPO:-}"
NEW_BRANCH="${NEW_BRANCH:-}"
DRY_RUN="${DRY_RUN:-false}"

usage() {
  cat <<EOF
Usage: $(basename "$0") [options]

Options:
  --repo owner/repo        Repository slug on GitHub/Quay/etc (in form owner/repo). If omitted, derived from git remote '$REMOTE'.
  --target-branch BRANCH   Target branch to base the new branch on (default: $TARGET_BRANCH)
  --author AUTHOR          PR author to filter (default: $AUTHOR)
  --new-branch BRANCH      Name for the new branch (default: autogenerated)
  --dry-run                Do not perform git operations, just show actions
  -h, --help               Show this help
EOF
  exit 1
}

# parse args
while [ $# -gt 0 ]; do
  case "$1" in
    --repo) REPO="$2"; shift 2;;
    --target-branch) TARGET_BRANCH="$2"; shift 2;;
    --author) AUTHOR="$2"; shift 2;;
    --new-branch) NEW_BRANCH="$2"; shift 2;;
    --dry-run) DRY_RUN=true; shift;;
    -h|--help) usage;;
    *) echo "Unknown arg: $1"; usage;;
  esac
done

command -v gh >/dev/null 2>&1 || { echo "gh CLI required. Install and authenticate (gh auth login)."; exit 2; }
command -v git >/dev/null 2>&1 || { echo "git required."; exit 2; }

# derive repo from git remote if not provided
if [ -z "$REPO" ]; then
  url=$(git remote get-url "$REMOTE" 2>/dev/null || true)
  if [ -z "$url" ]; then
    echo "Remote '$REMOTE' not found and --repo not provided."
    exit 2
  fi
  # handle ssh and https urls
  REPO=https://github.com/$(echo "$url" | sed -E 's#.*[:/](.+/.+?)(\.git)?$#\1#')
fi

if [ -z "$NEW_BRANCH" ]; then
  ts=$(date -u +"%Y%m%dT%H%M%SZ")
  NEW_BRANCH="aggregate-deps-${TARGET_BRANCH}-${ts}"
fi

echo "Repository: $REPO"
echo "Remote: $REMOTE"
echo "Target branch: $TARGET_BRANCH"
echo "Author filter: $AUTHOR"
echo "New branch: $NEW_BRANCH"
echo "Dry run: $DRY_RUN"
echo

# fetch latest
echo "Fetching remotes..."
if ! $DRY_RUN; then
  git fetch --all --prune
fi

# list open PRs and filter titles & exact base branch locally
echo "Querying PRs from gh and filtering titles and base branch..."
# request headRefOid so we can check commit status
ALL_PRS_JSON=$(gh pr list --repo "$REPO" --state open --author "$AUTHOR" --limit 1000 --json number,title,headRefName,headRefOid,baseRefName,labels 2>/dev/null | jq 'sort_by(.number)') || {
  echo "gh pr list failed"; exit 3
}
# keep PR objects where
# - baseRefName equals TARGET_BRANCH
# - title starts with "fix(deps)" or "chore(deps)"
# - do NOT have the labels "do-not-merge/hold" or "konflux-nudge"
CANDIDATE_PRS_JSON=$(echo "$ALL_PRS_JSON" | jq --arg target "$TARGET_BRANCH" '[
  .[] |
  select(
    .baseRefName == $target
    and (.title | test("^(fix|chore)\\(deps\\)"))
    and ( (.labels // [] | map(.name) | index("do-not-merge/hold") | not) )
    and ( (.labels // [] | map(.name) | index("konflux-nudge") | not) )
  )
]')

# If repo was derived as a URL convert to owner/repo for gh api paths
OWNER_REPO="$REPO"
OWNER_REPO=$(echo "$OWNER_REPO" | sed -E 's#^https?://##' | sed -E 's#^github.com/##' | sed -E 's#^git@github.com:##' | sed -E 's#\.git$##')

# Now check GitHub combined status for each PR head commit and exclude those with failing checks
FILTERED_PR_ARRAY=()
SKIPPED_BY_CHECKS=()
for prnum in $(echo "$CANDIDATE_PRS_JSON" | jq -r '.[].number'); do
  headsha=$(echo "$CANDIDATE_PRS_JSON" | jq -r --argjson n "$prnum" '.[] | select(.number == ($n|tonumber)) | .headRefOid')
  # if no head sha, skip conservatively
  if [ -z "$headsha" ] || [ "$headsha" = "null" ]; then
    echo "Skipping PR #$prnum: missing head SHA"
    SKIPPED_BY_CHECKS+=("$prnum")
    continue
  fi
  # query combined status (state: success, failure, pending, or error)
  state=$(gh api -H "Accept: application/vnd.github.v3+json" "/repos/${OWNER_REPO}/commits/${headsha}/status" 2>/dev/null | jq -r '.state' 2>/dev/null || echo "unknown")
  if [ "$state" = "failure" ]; then
    echo "Skipping PR #$prnum due to failing checks (state=$state)"
    SKIPPED_BY_CHECKS+=("$prnum")
    continue
  fi
  # keep PR if checks not failing
  pr_obj=$(echo "$CANDIDATE_PRS_JSON" | jq --argjson n "$prnum" '.[] | select(.number == ($n|tonumber))')
  FILTERED_PR_ARRAY+=("$pr_obj")
done

# Rebuild PRS_JSON from FILTERED_PR_ARRAY
if [ "${#FILTERED_PR_ARRAY[@]}" -eq 0 ]; then
  echo "No PRs remain after checks-filtering."
  exit 0
fi

# create a JSON array string for PRS_JSON
PRS_JSON=$(printf '%s\n' "${FILTERED_PR_ARRAY[@]}" | jq -s '.')
# optional: show skipped PRs due to failing checks
if [ "${#SKIPPED_BY_CHECKS[@]}" -gt 0 ]; then
  echo "PRs skipped because of failing checks: ${SKIPPED_BY_CHECKS[*]}"
fi

PR_COUNT=$(echo "$PRS_JSON" | jq 'length')
if [ "$PR_COUNT" -eq 0 ]; then
  echo "No PRs found matching criteria."
  exit 0
fi

echo "Found $PR_COUNT PR(s)."
PR_NUMS=$(echo "$PRS_JSON" | jq -r '.[].number')

# create new branch from remote target
echo "Creating new branch '$NEW_BRANCH' from '$REMOTE/$TARGET_BRANCH'..."
if $DRY_RUN; then
  echo "[dry-run] git checkout -b $NEW_BRANCH $REMOTE/$TARGET_BRANCH"
else
  git checkout -B "$NEW_BRANCH" "$REMOTE/$TARGET_BRANCH"
fi

picked=()
skipped=()

# iterate PRs and cherry-pick their commits in order
for pr in $PR_NUMS; do
  echo
  # get PR title for reporting
  pr_title=$(echo "$PRS_JSON" | jq -r --argjson n "$pr" '.[] | select(.number == ($n|tonumber)) | .title' )
  echo "Processing PR #$pr - ${pr_title} ..."
  # get commits for PR
  commits=$(gh pr view "$pr" --repo "$REPO" --json commits --jq '.commits[].oid' 2>/dev/null) || {
    echo "  failed to retrieve commits for PR #$pr, skipping."
    continue
  }
  # fetch PR head ref to ensure commits are available locally (may be from a fork)
  headref=$(echo "$PRS_JSON" | jq -r --argjson n "$pr" '.[] | select(.number == ($n|tonumber)) | .headRefName' )
  if [ -n "$headref" ] && ! $DRY_RUN; then
    # try fetch the headRef from remote if present
    git fetch "$REMOTE" "+refs/heads/$headref:refs/remotes/$REMOTE/$headref" 2>/dev/null || true
  fi

  for sha in $commits; do
    echo "  Commit: $sha (from PR #$pr)"
    # skip if already contained in branch
    if git merge-base --is-ancestor "$sha" HEAD 2>/dev/null; then
      echo "    already present in branch; skipping."
      skipped+=("${pr}|${sha}|${pr_title}")
      continue
    fi

    if $DRY_RUN; then
      echo "    [dry-run] git cherry-pick $sha"
      picked+=("${pr}|${sha}|${pr_title}")
      continue
    fi

    # attempt cherry-pick
    if git cherry-pick "$sha"; then
      echo "    cherry-pick succeeded."
      picked+=("${pr}|${sha}|${pr_title}")
    else
      echo "    conflict or error during cherry-pick; aborting this cherry-pick and skipping commit."
      git cherry-pick --abort >/dev/null 2>&1 || true
      skipped+=("${pr}|${sha}|${pr_title}")
    fi
  done
done

echo
echo "Summary:"
echo "  New branch: $NEW_BRANCH (local only)"
echo "  Commits picked: ${#picked[@]}"
for entry in "${picked[@]}"; do
  IFS='|' read -r pr sha title <<< "$entry"
  echo "    PR #${pr}  ${sha}  - ${title}"
done
echo "  Commits skipped: ${#skipped[@]}"
for entry in "${skipped[@]}"; do
  IFS='|' read -r pr sha title <<< "$entry"
  echo "    PR #${pr}  ${sha}  - ${title}"
done

echo
echo "Done. The branch '$NEW_BRANCH' is ready locally. No push was performed."
