apiVersion: v1
kind: ConfigMap
metadata:
  name: kata-addon-artifacts
  namespace: openshift-sandboxed-containers-operator
data:
  addonImage: "quay.io/openshift_sandboxed_containers/kata-se-artifacts:v1.0"
  
  # Path within the container image where kernel is located
  kernelPath: "/artifacts/kernel/vmlinuz"
