apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  annotations:
    build.appstudio.openshift.io/repo: https://github.com/openshift/sandboxed-containers-operator?rev={{revision}}
    build.appstudio.redhat.com/commit_sha: '{{revision}}'
    build.appstudio.redhat.com/target_branch: '{{target_branch}}'
    pipelinesascode.tekton.dev/cancel-in-progress: 'false'
    pipelinesascode.tekton.dev/max-keep-runs: '3'
    pipelinesascode.tekton.dev/on-cel-expression: event == "push" &&
      target_branch == "devel" &&
      ( "config/peerpods/podvm/***".pathChanged() ||
        ".tekton/osc-podvm-builder-push.yaml".pathChanged() ||
        ".tekton/build-pipeline.yaml".pathChanged()
      )
  creationTimestamp:
  labels:
    appstudio.openshift.io/application: openshift-sandboxed-containers
    appstudio.openshift.io/component: osc-podvm-builder
    pipelines.appstudio.openshift.io/type: build
  name: osc-podvm-builder-on-push
  namespace: ose-osc-tenant
spec:
  params:
  - name: git-url
    value: '{{source_url}}'
  - name: revision
    value: '{{revision}}'
  - name: output-image
    value: quay.io/redhat-user-workloads/ose-osc-tenant/osc-podvm-builder:{{revision}}
  - name: build-platforms
    value:
    - linux/x86_64
    - linux/s390x
  - name: dockerfile
    value: Dockerfile.podvm-builder
  - name: path-context
    value: config/peerpods/podvm
  - name: build-args-file
    value: .tekton/build-args.env
  - name: prefetch-input
    value: '{"type": "rpm", "path": "./config/peerpods/podvm/"}'
  pipelineRef:
    name: build-pipeline
  taskRunTemplate:
    serviceAccountName: build-pipeline-osc-podvm-builder
  workspaces:
  - name: git-auth
    secret:
      secretName: '{{ git_auth_secret }}'
status: {}
