apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  annotations:
    build.appstudio.openshift.io/repo: https://github.com/openshift/sandboxed-containers-operator?rev={{revision}}
    build.appstudio.redhat.com/commit_sha: '{{revision}}'
    build.appstudio.redhat.com/pull_request_number: '{{pull_request_number}}'
    build.appstudio.redhat.com/target_branch: '{{target_branch}}'
    pipelinesascode.tekton.dev/cancel-in-progress: "true"
    pipelinesascode.tekton.dev/max-keep-runs: "3"
    pipelinesascode.tekton.dev/on-cel-expression: event == "pull_request" && target_branch
      == "devel" && ( "scripts/kata-install/***".pathChanged() || ".tekton/osc-daemonset-pull-request.yaml".pathChanged()
      || ".tekton/build-pipeline.yaml".pathChanged() )
  labels:
    appstudio.openshift.io/application: openshift-sandboxed-containers
    appstudio.openshift.io/component: osc-daemonset
    pipelines.appstudio.openshift.io/type: build
  name: osc-daemonset-on-pull-request
  namespace: ose-osc-tenant
spec:
  params:
  - name: git-url
    value: '{{source_url}}'
  - name: revision
    value: '{{revision}}'
  - name: output-image
    value: quay.io/redhat-user-workloads/ose-osc-tenant/osc-daemonset:on-pr-{{revision}}
  - name: image-expires-after
    value: 5d
  - name: build-platforms
    value:
    - linux/x86_64
  - name: dockerfile
    value: Dockerfile
  - name: path-context
    value: scripts/kata-install
  - name: hermetic
    value: "false"
  - name: additional-tags
    value:
    - pr-{{pull_request_number}}
    - pullreq-{{pull_request_number}}-{{revision}}
  - name: sast-target-dirs
    value: scripts/kata-install
  pipelineRef:
    name: build-pipeline
  taskRunTemplate:
    serviceAccountName: build-pipeline-osc-daemonset
  workspaces:
  - name: git-auth
    secret:
      secretName: '{{ git_auth_secret }}'
status: {}
