#!/bin/bash

IFS=$'\n'

BASE_COLLECTION_PATH="/must-gather"

# kataconfig
OSC_PATH=${BASE_COLLECTION_PATH}/sandboxed-containers
mkdir -p ${OSC_PATH}

oc describe kataconfig > "${OSC_PATH}/kataconfig_description"

# operators
operators=()
#  logs from everything in the following operators namespaces
#  - openshift-sandboxed-containers-operator
#  - openshift-machine-config-operator
operators+=(openshift-sandboxed-containers-operator)
operators+=(openshift-machine-config-operator)

NAMESPACE_PATH=${OSC_PATH}/namespaces
for operator in "${operators[@]}"; do
    OPERATOR_NS=${NAMESPACE_PATH}/${operator}
    mkdir -p ${OPERATOR_NS}

    for pod in $(oc get pods -n "${operator}" -o'custom-columns=name:metadata.name' --no-headers); do
        oc logs "${pod}" -n "${operator}" > "${OPERATOR_NS}/${pod}_logs"
    done
done

# mcps
mcps=()
#  description of the following mcps
#  - master
#  - worker
#  - kata-oc
mcps+=(master)
mcps+=(worker)
mcps+=(kata-oc)

MCP_PATH=${OSC_PATH}/mcps
mkdir -p ${MCP_PATH}

for mcp in "${mcps[@]}"; do
    if $(oc get mcp $mcp &>/dev/null); then
        oc describe mcp $mcp > "${MCP_PATH}/${mcp}_description"
    fi	    
done
