apiVersion: cloudcredential.openshift.io/v1
kind: CredentialsRequest
metadata:
  name: openshift-sandboxed-containers-aws
  namespace: openshift-cloud-credential-operator
spec:
  secretRef:
    name: cco-secret
    namespace: openshift-sandboxed-containers-operator
  serviceAccountNames:
    - default
  providerSpec:
    apiVersion: cloudcredential.openshift.io/v1
    kind: AWSProviderSpec
    statementEntries:
      - effect: Allow
        action:
          - ec2:*
        resource: "*"

      ##### Below is Extended Policy: Image Creation Operations #####

      # VMImport Role Management
      - effect: Allow
        action:
          - iam:CreateRole
          - iam:PutRolePolicy
          - iam:GetRole
          - iam:ListRolePolicies
          - iam:DeleteRole
          - iam:DeleteRolePolicy
        resource: "arn:aws:iam::*:role/vmimport"

      # S3 Bucket Management
      - effect: Allow
        action:
          - s3:CreateBucket
          - s3:DeleteBucket
          - s3:GetBucketLocation
          - s3:ListBucket
          - s3:GetBucketAcl
        resource: "arn:aws:s3:::podvm-*"

      # S3 Object Management
      - effect: Allow
        action:
          - s3:PutObject
          - s3:GetObject
          - s3:DeleteObject
        resource: "arn:aws:s3:::podvm-*/*"

      # S3 List All Buckets
      - effect: Allow
        action:
          - s3:ListAllMyBuckets
        resource: "*"
