apiVersion: cloudcredential.openshift.io/v1
kind: CredentialsRequest
metadata:
  name: openshift-sandboxed-containers-azure
  namespace: openshift-cloud-credential-operator
spec:
  secretRef:
    name: cco-secret
    namespace: openshift-sandboxed-containers-operator
  serviceAccountNames:
    - default
  providerSpec:
    apiVersion: cloudcredential.openshift.io/v1
    kind: AzureProviderSpec
    roleBindings:
      # Runtime permissions required by cloud-api-adaptor
      - role: Reader
      - role: Virtual Machine Contributor
      - role: Network Contributor

      ##### Below is Extended Policy: Image Creation Operations #####

      # Storage and Compute Gallery permissions for image creation
      - role: Storage Account Contributor
      - role: Compute Gallery Artifacts Publisher
